// Mock data for WhoKnows Models
// This will be used for initial rendering and can be replaced with database data

export const mockModels = [
  // Women Models
  {
    id: '1',
    name: 'Sarah Chen',
    slug: 'sarah-chen',
    gender: 'women' as const,
    height: "5'10\" / 178cm",
    chest: '32"',
    waist: '24"',
    hips: '35"',
    hair: 'Black',
    eyes: 'Brown',
    location: 'Jakarta, Indonesia',
    bio: 'Sarah is a rising star in the Asian fashion industry, known for her versatile look and elegant presence on the runway.',
    featured: true,
    order: 1,
    images: [
      { id: '1-1', modelId: '1', imageUrl: '/models/women/sarah-chen-1.jpg', alt: 'Sarah Chen - Portrait', order: 1, isPrimary: true },
      { id: '1-2', modelId: '1', imageUrl: '/models/women/sarah-chen-2.jpg', alt: 'Sarah Chen - Editorial', order: 2, isPrimary: false },
      { id: '1-3', modelId: '1', imageUrl: '/models/women/sarah-chen-3.jpg', alt: 'Sarah Chen - Runway', order: 3, isPrimary: false },
    ],
  },
  {
    id: '2',
    name: 'Emma Rodriguez',
    slug: 'emma-rodriguez',
    gender: 'women' as const,
    height: "5'11\" / 180cm",
    chest: '33"',
    waist: '24"',
    hips: '36"',
    hair: 'Brown',
    eyes: 'Green',
    location: 'Barcelona, Spain',
    bio: 'Emma brings a unique European flair to every shoot, with experience in haute couture and commercial work.',
    featured: true,
    order: 2,
    images: [
      { id: '2-1', modelId: '2', imageUrl: '/models/women/emma-rodriguez-1.jpg', alt: 'Emma Rodriguez - Portrait', order: 1, isPrimary: true },
      { id: '2-2', modelId: '2', imageUrl: '/models/women/emma-rodriguez-2.jpg', alt: 'Emma Rodriguez - Editorial', order: 2, isPrimary: false },
    ],
  },
  {
    id: '3',
    name: 'Aisha Patel',
    slug: 'aisha-patel',
    gender: 'women' as const,
    height: "5'9\" / 175cm",
    chest: '31"',
    waist: '23"',
    hips: '34"',
    hair: 'Dark Brown',
    eyes: 'Brown',
    location: 'Mumbai, India',
    bio: 'Aisha represents the new wave of international models breaking barriers across global fashion capitals.',
    featured: true,
    order: 3,
    images: [
      { id: '3-1', modelId: '3', imageUrl: '/models/women/aisha-patel-1.jpg', alt: 'Aisha Patel - Portrait', order: 1, isPrimary: true },
      { id: '3-2', modelId: '3', imageUrl: '/models/women/aisha-patel-2.jpg', alt: 'Aisha Patel - Editorial', order: 2, isPrimary: false },
    ],
  },
  {
    id: '4',
    name: 'Maya Tanaka',
    slug: 'maya-tanaka',
    gender: 'women' as const,
    height: "5'8\" / 173cm",
    chest: '32"',
    waist: '24"',
    hips: '34"',
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Tokyo, Japan',
    bio: 'Maya combines traditional Japanese elegance with contemporary fashion sensibilities.',
    featured: false,
    order: 4,
    images: [
      { id: '4-1', modelId: '4', imageUrl: '/models/women/maya-tanaka-1.jpg', alt: 'Maya Tanaka - Portrait', order: 1, isPrimary: true },
    ],
  },
  {
    id: '5',
    name: 'Olivia Smith',
    slug: 'olivia-smith',
    gender: 'women' as const,
    height: "5'10\" / 178cm",
    chest: '33"',
    waist: '25"',
    hips: '35"',
    hair: 'Blonde',
    eyes: 'Blue',
    location: 'Sydney, Australia',
    bio: 'Olivia brings Australian sunshine to every runway with her radiant presence.',
    featured: true,
    order: 5,
    images: [
      { id: '5-1', modelId: '5', imageUrl: '/models/women/olivia-smith-1.jpg', alt: 'Olivia Smith - Portrait', order: 1, isPrimary: true },
      { id: '5-2', modelId: '5', imageUrl: '/models/women/olivia-smith-2.jpg', alt: 'Olivia Smith - Beach Editorial', order: 2, isPrimary: false },
    ],
  },
  {
    id: '6',
    name: 'Priya Sharma',
    slug: 'priya-sharma',
    gender: 'women' as const,
    height: "5'9\" / 175cm",
    chest: '32"',
    waist: '24"',
    hips: '35"',
    hair: 'Black',
    eyes: 'Brown',
    location: 'New Delhi, India',
    bio: 'Priya is a versatile model excelling in both traditional and contemporary fashion.',
    featured: false,
    order: 6,
    images: [
      { id: '6-1', modelId: '6', imageUrl: '/models/women/priya-sharma-1.jpg', alt: 'Priya Sharma - Portrait', order: 1, isPrimary: true },
    ],
  },
  // Men Models
  {
    id: '7',
    name: 'James Morrison',
    slug: 'james-morrison',
    gender: 'men' as const,
    height: "6'2\" / 188cm",
    chest: '40"',
    waist: '32"',
    hips: '38"',
    hair: 'Brown',
    eyes: 'Blue',
    location: 'London, UK',
    bio: 'James is a seasoned runway model with a commanding presence and editorial experience.',
    featured: true,
    order: 1,
    images: [
      { id: '7-1', modelId: '7', imageUrl: '/models/men/james-morrison-1.jpg', alt: 'James Morrison - Portrait', order: 1, isPrimary: true },
      { id: '7-2', modelId: '7', imageUrl: '/models/men/james-morrison-2.jpg', alt: 'James Morrison - Editorial', order: 2, isPrimary: false },
    ],
  },
  {
    id: '8',
    name: 'Kai Nakamura',
    slug: 'kai-nakamura',
    gender: 'men' as const,
    height: "6'1\" / 185cm",
    chest: '39"',
    waist: '31"',
    hips: '36"',
    hair: 'Black',
    eyes: 'Brown',
    location: 'Seoul, South Korea',
    bio: 'Kai represents the modern Asian male aesthetic, blending streetwear with high fashion.',
    featured: true,
    order: 2,
    images: [
      { id: '8-1', modelId: '8', imageUrl: '/models/men/kai-nakamura-1.jpg', alt: 'Kai Nakamura - Portrait', order: 1, isPrimary: true },
      { id: '8-2', modelId: '8', imageUrl: '/models/men/kai-nakamura-2.jpg', alt: 'Kai Nakamura - Editorial', order: 2, isPrimary: false },
    ],
  },
  {
    id: '9',
    name: 'Marco Rossi',
    slug: 'marco-rossi',
    gender: 'men' as const,
    height: "6'3\" / 190cm",
    chest: '41"',
    waist: '33"',
    hips: '39"',
    hair: 'Dark Brown',
    eyes: 'Brown',
    location: 'Milan, Italy',
    bio: 'Marco brings Italian sophistication to every campaign with his classic features.',
    featured: true,
    order: 3,
    images: [
      { id: '9-1', modelId: '9', imageUrl: '/models/men/marco-rossi-1.jpg', alt: 'Marco Rossi - Portrait', order: 1, isPrimary: true },
      { id: '9-2', modelId: '9', imageUrl: '/models/men/marco-rossi-2.jpg', alt: 'Marco Rossi - Editorial', order: 2, isPrimary: false },
    ],
  },
  {
    id: '10',
    name: 'David Kim',
    slug: 'david-kim',
    gender: 'men' as const,
    height: "6'0\" / 183cm",
    chest: '38"',
    waist: '30"',
    hips: '35"',
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Los Angeles, USA',
    bio: 'David is known for his athletic build and versatile look, from sportswear to formal wear.',
    featured: false,
    order: 4,
    images: [
      { id: '10-1', modelId: '10', imageUrl: '/models/men/david-kim-1.jpg', alt: 'David Kim - Portrait', order: 1, isPrimary: true },
    ],
  },
  {
    id: '11',
    name: 'Rafael Santos',
    slug: 'rafael-santos',
    gender: 'men' as const,
    height: "6'1\" / 185cm",
    chest: '40"',
    waist: '32"',
    hips: '37"',
    hair: 'Black',
    eyes: 'Brown',
    location: 'São Paulo, Brazil',
    bio: 'Rafael brings Brazilian energy and passion to the global fashion scene.',
    featured: true,
    order: 5,
    images: [
      { id: '11-1', modelId: '11', imageUrl: '/models/men/rafael-santos-1.jpg', alt: 'Rafael Santos - Portrait', order: 1, isPrimary: true },
      { id: '11-2', modelId: '11', imageUrl: '/models/men/rafael-santos-2.jpg', alt: 'Rafael Santos - Beach Editorial', order: 2, isPrimary: false },
    ],
  },
  {
    id: '12',
    name: 'Ahmed Hassan',
    slug: 'ahmed-hassan',
    gender: 'men' as const,
    height: "6'0\" / 183cm",
    chest: '39"',
    waist: '31"',
    hips: '36"',
    hair: 'Black',
    eyes: 'Brown',
    location: 'Dubai, UAE',
    bio: 'Ahmed represents the emerging Middle Eastern fashion market with distinction.',
    featured: false,
    order: 6,
    images: [
      { id: '12-1', modelId: '12', imageUrl: '/models/men/ahmed-hassan-1.jpg', alt: 'Ahmed Hassan - Portrait', order: 1, isPrimary: true },
    ],
  },
];

export const mockCampaigns = [
  {
    id: '1',
    title: 'Summer Escape 2024',
    slug: 'summer-escape-2024',
    description: 'A vibrant summer campaign featuring our top models in tropical locations. This campaign captures the essence of summer freedom and adventure.',
    client: 'Luxe Magazine',
    year: '2024',
    coverImage: '/campaigns/summer-escape-cover.jpg',
    order: 1,
    models: [{ model: mockModels[0] }, { model: mockModels[4] }, { model: mockModels[10] }],
    images: [
      { id: 'c1-1', campaignId: '1', imageUrl: '/campaigns/summer-escape-1.jpg', alt: 'Summer Escape Campaign 1', order: 1 },
      { id: 'c1-2', campaignId: '1', imageUrl: '/campaigns/summer-escape-2.jpg', alt: 'Summer Escape Campaign 2', order: 2 },
      { id: 'c1-3', campaignId: '1', imageUrl: '/campaigns/summer-escape-3.jpg', alt: 'Summer Escape Campaign 3', order: 3 },
    ],
  },
  {
    id: '2',
    title: 'Urban Edge',
    slug: 'urban-edge',
    description: 'Street style meets high fashion in this urban-inspired campaign. Bold, edgy, and unapologetically modern.',
    client: 'Vogue Asia',
    year: '2024',
    coverImage: '/campaigns/urban-edge-cover.jpg',
    order: 2,
    models: [{ model: mockModels[1] }, { model: mockModels[6] }],
    images: [
      { id: 'c2-1', campaignId: '2', imageUrl: '/campaigns/urban-edge-1.jpg', alt: 'Urban Edge Campaign 1', order: 1 },
      { id: 'c2-2', campaignId: '2', imageUrl: '/campaigns/urban-edge-2.jpg', alt: 'Urban Edge Campaign 2', order: 2 },
    ],
  },
  {
    id: '3',
    title: 'Ethereal Dreams',
    slug: 'ethereal-dreams',
    description: 'A dreamy editorial showcasing romantic and ethereal fashion. Soft lighting and flowing fabrics create a magical atmosphere.',
    client: 'Harper\'s Bazaar',
    year: '2023',
    coverImage: '/campaigns/ethereal-dreams-cover.jpg',
    order: 3,
    models: [{ model: mockModels[2] }, { model: mockModels[3] }],
    images: [
      { id: 'c3-1', campaignId: '3', imageUrl: '/campaigns/ethereal-dreams-1.jpg', alt: 'Ethereal Dreams Campaign 1', order: 1 },
      { id: 'c3-2', campaignId: '3', imageUrl: '/campaigns/ethereal-dreams-2.jpg', alt: 'Ethereal Dreams Campaign 2', order: 2 },
    ],
  },
  {
    id: '4',
    title: 'Noir Elegance',
    slug: 'noir-elegance',
    description: 'A sophisticated black and white campaign celebrating timeless elegance. Classic beauty meets contemporary style.',
    client: 'Elle Magazine',
    year: '2023',
    coverImage: '/campaigns/noir-elegance-cover.jpg',
    order: 4,
    models: [{ model: mockModels[8] }, { model: mockModels[7] }],
    images: [
      { id: 'c4-1', campaignId: '4', imageUrl: '/campaigns/noir-elegance-1.jpg', alt: 'Noir Elegance Campaign 1', order: 1 },
      { id: 'c4-2', campaignId: '4', imageUrl: '/campaigns/noir-elegance-2.jpg', alt: 'Noir Elegance Campaign 2', order: 2 },
    ],
  },
];

export const mockHeroSlides = [
  {
    id: '1',
    title: 'Discover Excellence',
    subtitle: 'International modelling agency representing the finest talent worldwide',
    imageUrl: '/hero/hero-1.jpg',
    link: '/women',
    order: 1,
    active: true,
  },
  {
    id: '2',
    title: 'New Faces 2024',
    subtitle: 'Meet our latest signings making waves in the fashion industry',
    imageUrl: '/hero/hero-2.jpg',
    link: '/men',
    order: 2,
    active: true,
  },
  {
    id: '3',
    title: 'Join Our Roster',
    subtitle: 'Apply now and start your modelling journey with us',
    imageUrl: '/hero/hero-3.jpg',
    link: '/apply',
    order: 3,
    active: true,
  },
];

export const mockClients = [
  { id: '1', name: 'Vogue', logoUrl: '/clients/vogue.svg', order: 1, active: true },
  { id: '2', name: 'Harper\'s Bazaar', logoUrl: '/clients/harpers.svg', order: 2, active: true },
  { id: '3', name: 'Elle', logoUrl: '/clients/elle.svg', order: 3, active: true },
  { id: '4', name: 'GQ', logoUrl: '/clients/gq.svg', order: 4, active: true },
  { id: '5', name: 'L\'Officiel', logoUrl: '/clients/lofficiel.svg', order: 5, active: true },
  { id: '6', name: 'Numéro', logoUrl: '/clients/numero.svg', order: 6, active: true },
];
