// Mock data for WhoKnows Models
// This will be used for initial rendering and can be replaced with database data

export const mockModels = [
  {
    id: 'm1',
    name: 'Ahmed Hassan',
    slug: 'ahmed-hassan',
    gender: 'men' as const,
    height: '188cm / 6\'2"',
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'Dubai',
    bio: null,
    featured: true,
    order: 1,
    images: [{ id: 'mi1', modelId: 'm1', imageUrl: '/models/men/ahmed-hassan-1.jpg', alt: 'Ahmed Hassan', order: 1, isPrimary: true }],
  },
  {
    id: 'm2',
    name: 'David Kim',
    slug: 'david-kim',
    gender: 'men' as const,
    height: '185cm / 6\'1"',
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'Seoul',
    bio: null,
    featured: true,
    order: 2,
    images: [{ id: 'mi2', modelId: 'm2', imageUrl: '/models/men/david-kim-1.jpg', alt: 'David Kim', order: 1, isPrimary: true }],
  },
  {
    id: 'w1',
    name: 'Aisha Patel',
    slug: 'aisha-patel',
    gender: 'women' as const,
    height: '178cm / 5\'10"',
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'Mumbai',
    bio: null,
    featured: true,
    order: 3,
    images: [{ id: 'mi3', modelId: 'w1', imageUrl: '/models/women/aisha-patel-1.jpg', alt: 'Aisha Patel', order: 1, isPrimary: true }],
  },
  {
    id: 'w2',
    name: 'Emma Rodriguez',
    slug: 'emma-rodriguez',
    gender: 'women' as const,
    height: '175cm / 5\'9"',
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'Madrid',
    bio: null,
    featured: true,
    order: 4,
    images: [{ id: 'mi4', modelId: 'w2', imageUrl: '/models/women/emma-rodriguez-1.jpg', alt: 'Emma Rodriguez', order: 1, isPrimary: true }],
  },
  {
    id: 'm3',
    name: 'James Morrison',
    slug: 'james-morrison',
    gender: 'men' as const,
    height: '187cm / 6\'1.5"',
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'London',
    bio: null,
    featured: false,
    order: 5,
    images: [{ id: 'mi5', modelId: 'm3', imageUrl: '/models/men/james-morrison-1.jpg', alt: 'James Morrison', order: 1, isPrimary: true }],
  },
  {
    id: 'w3',
    name: 'Maya Tanaka',
    slug: 'maya-tanaka',
    gender: 'women' as const,
    height: '176cm / 5\'9.5"',
    chest: null,
    waist: null,
    hips: null,
    hair: null,
    eyes: null,
    location: 'Tokyo',
    bio: null,
    featured: false,
    order: 6,
    images: [{ id: 'mi6', modelId: 'w3', imageUrl: '/models/women/maya-tanaka-1.jpg', alt: 'Maya Tanaka', order: 1, isPrimary: true }],
  },
];

export const mockCampaigns = [
  {
    id: '1',
    title: 'Summer Escape 2024',
    slug: 'summer-escape-2024',
    description: 'A vibrant summer campaign featuring our top models in tropical locations. This campaign captures the essence of summer freedom and adventure.',
    client: 'Luxe Magazine',
    year: '2024',
    coverImage: '/campaigns/summer-escape-cover.jpg',
    order: 1,
    models: [{ model: mockModels[0] }, { model: mockModels[4] }, { model: mockModels[5] }],
    images: [
      { id: 'c1-1', campaignId: '1', imageUrl: '/campaigns/summer-escape-1.jpg', alt: 'Summer Escape Campaign 1', order: 1 },
      { id: 'c1-2', campaignId: '1', imageUrl: '/campaigns/summer-escape-2.jpg', alt: 'Summer Escape Campaign 2', order: 2 },
      { id: 'c1-3', campaignId: '1', imageUrl: '/campaigns/summer-escape-3.jpg', alt: 'Summer Escape Campaign 3', order: 3 },
    ],
  },
  {
    id: '2',
    title: 'Urban Edge',
    slug: 'urban-edge',
    description: 'Street style meets high fashion in this urban-inspired campaign. Bold, edgy, and unapologetically modern.',
    client: 'Vogue Asia',
    year: '2024',
    coverImage: '/campaigns/urban-edge-cover.jpg',
    order: 2,
    models: [{ model: mockModels[1] }, { model: mockModels[2] }],
    images: [
      { id: 'c2-1', campaignId: '2', imageUrl: '/campaigns/urban-edge-1.jpg', alt: 'Urban Edge Campaign 1', order: 1 },
      { id: 'c2-2', campaignId: '2', imageUrl: '/campaigns/urban-edge-2.jpg', alt: 'Urban Edge Campaign 2', order: 2 },
    ],
  },
  {
    id: '3',
    title: 'Ethereal Dreams',
    slug: 'ethereal-dreams',
    description: 'A dreamy editorial showcasing romantic and ethereal fashion. Soft lighting and flowing fabrics create a magical atmosphere.',
    client: 'Harper\'s Bazaar',
    year: '2023',
    coverImage: '/campaigns/ethereal-dreams-cover.jpg',
    order: 3,
    models: [{ model: mockModels[2] }, { model: mockModels[3] }],
    images: [
      { id: 'c3-1', campaignId: '3', imageUrl: '/campaigns/ethereal-dreams-1.jpg', alt: 'Ethereal Dreams Campaign 1', order: 1 },
      { id: 'c3-2', campaignId: '3', imageUrl: '/campaigns/ethereal-dreams-2.jpg', alt: 'Ethereal Dreams Campaign 2', order: 2 },
    ],
  },
  {
    id: '4',
    title: 'Noir Elegance',
    slug: 'noir-elegance',
    description: 'A sophisticated black and white campaign celebrating timeless elegance. Classic beauty meets contemporary style.',
    client: 'Elle Magazine',
    year: '2023',
    coverImage: '/campaigns/noir-elegance-cover.jpg',
    order: 4,
    models: [{ model: mockModels[0] }, { model: mockModels[1] }],
    images: [
      { id: 'c4-1', campaignId: '4', imageUrl: '/campaigns/noir-elegance-1.jpg', alt: 'Noir Elegance Campaign 1', order: 1 },
      { id: 'c4-2', campaignId: '4', imageUrl: '/campaigns/noir-elegance-2.jpg', alt: 'Noir Elegance Campaign 2', order: 2 },
    ],
  },
];

export const mockHeroSlides = [
  {
    id: '1',
    title: 'Discover Excellence',
    subtitle: 'International modelling agency representing the finest talent worldwide',
    imageUrl: '/hero/hero-1.jpg',
    link: '/women',
    order: 1,
    active: true,
  },
  {
    id: '2',
    title: 'New Faces 2024',
    subtitle: 'Meet our latest signings making waves in the fashion industry',
    imageUrl: '/hero/hero-2.jpg',
    link: '/men',
    order: 2,
    active: true,
  },
  {
    id: '3',
    title: 'Join Our Roster',
    subtitle: 'Apply now and start your modelling journey with us',
    imageUrl: '/hero/hero-3.jpg',
    link: '/apply',
    order: 3,
    active: true,
  },
];

export const mockClients = [
  { id: '1', name: 'Vogue', logoUrl: '/clients/vogue.svg', order: 1, active: true },
  { id: '2', name: 'Harper\'s Bazaar', logoUrl: '/clients/harpers.svg', order: 2, active: true },
  { id: '3', name: 'Elle', logoUrl: '/clients/elle.svg', order: 3, active: true },
  { id: '4', name: 'GQ', logoUrl: '/clients/gq.svg', order: 4, active: true },
  { id: '5', name: 'L\'Officiel', logoUrl: '/clients/lofficiel.svg', order: 5, active: true },
  { id: '6', name: 'Numéro', logoUrl: '/clients/numero.svg', order: 6, active: true },
];
